import type { NextPage } from "next";
import Head from "next/head";
import VLibras from "vlibras-nextjs";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			{/* only worked in production in tests with nextjs applications, maybe you can solve this! */}
			{process.env.NODE_ENV === "production" && <VLibras forceOnload />}
			<Head>
				<title>vlibras-nextjs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Bem vindo ao exemplo da lib{" "}
					<a target="_blank" rel="noreferrer" href="https://github.com/vandsonfalcao/vlibras-nextjs">
						vlibras-nextjs
					</a>{" "}
					em aplicações <a target="_blank" rel="noreferrer" href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>

			<footer className={styles.footer}>
				<a target="_blank" rel="noreferrer" href="https://github.com/vandsonfalcao">Powered by Vandson Falcão</a>
			</footer>
		</div>
	);
};

export default Home;
